### ISSUE TITLE
Maybe change event names from past participles (PriceChanged) to nouns (PriceChange)?

### ISSUE THREAD

**Issue by jacob-eliosoff** [usmfum/USM#120]
ABDK think this is more conventional, I see some mixed evidence but on balance I agree.

**Comment by albertocuestacanada** [comment]
Up to you, I've always found that using nouns makes naming events a bit more difficult, and sometimes clash with contract names. I prefer past tenses.

**Comment by jacob-eliosoff** [comment]
Yeah OK let's stick with it as is.  Just wanted to check we weren't mixing randomly.
