### ISSUE TITLE
Integrate Uniswap v2 oracle

### ISSUE THREAD

**Issue by albertocuestacanada** [usmfum/USM#27]
Let's check what our options are

**Comment by albertocuestacanada** [comment]
Try using this, and learn.

https://github.com/Keydonix/uniswap-oracle/blob/master/README.md

**Comment by alexroan** [comment]
Yep, this Keydonix repo is what I found when we were looking at oracles a few weeks back. It looks like the easiest method for implementing Uniswap oracles for us.

**Comment by jacob-eliosoff** [comment]
Ah yeah I actually had an [exchange](https://medium.com/@epheph/youre-welcome-60924a9cf640) with Scott from Keydonix about this last week.  Does sound like the most promising Uniswap approach for us.

**Comment by jacob-eliosoff** [comment]
This seems like the sort of thing we could probably implement in ~20 lines of (library-using) code.  Coming up with those 20 lines however...  😂

**Comment by alexroan** [comment]
This is difficult because as mentioned in [this tweet](https://twitter.com/RyanSAdams/status/1309485651608436738), Dai is no longer decentralized as its main collateral is a centralized token.

If we use Uniswap V2 token pairs like ETH-USDT, are we relying on centralization just as much? If Tether goes under, so does USM.

**Comment by alexroan** [comment]
I'll leave this here: [Chainlink Price Feeds Model](https://docs.chain.link/docs/architecture-decentralized-model)

**Comment by alexroan** [comment]
Going down the composite Oracle route, let's say we use ETH/USD Price Feed and USDC/ETH Uniswap V2 pair, the Price Feed actually returns a lot more information about the latest round. For example, we can get back the timestamp at which the price was updated.

Our composite could check the Price Feed and its timestamp, if it's older than _x_ then use the Uniswap pair price.

If the worry is that every Chainlink node goes down or a quorum is not reached to update the price, then default to the on-chain price. Obviously, that adds a new risk in that we're reliant on whatever Uniswap V2 pair we choose in the worst-case scenario.

**Comment by albertocuestacanada** [comment]
Fixed in #50
