### ISSUE TITLE
Off-chain signatures in UI

### ISSUE THREAD

**Issue by alexroan** [usmfum/USM#32]
For better UX, the UI should make use of off-chain signatures and use them to interact with ERC20Permit.

**Comment by albertocuestacanada** [comment]
Be aware that right now an `addDelegate` call or signature is required for each one of the four main USM functions. That's bad UX and I'm planning to fix it by coding a `batchDelegateByPermit(address holder, address delegate, bytes4[] signature, uint expiry, uint8 v, bytes32 r, bytes32 s)` function in `Delegable.sol`

**Comment by jacob-eliosoff** [comment]
This is over my head but fewer clicks = good!

**Comment by alexroan** [comment]
Thanks, @albertocuestacanada. We may have to sync up when this comes around.

This is reliant on #30 being merged first.
