### ISSUE TITLE
Constants in USM.sol or IUSM.sol?

### ISSUE THREAD

**Issue by jacob-eliosoff** [usmfum/USM#42]
This is total nitpicking but just for my understanding - we have the `enum Side {Buy, Sell}` in IUSM, but the constants like `WAD` and `MAX_DEBT_RATIO`, and the `struct TimedValue` definition, in USM.  Any rhyme or reason to that or does it just not matter much...

**Comment by albertocuestacanada** [comment]
The interface only contains the functions that are necessary to interact with `USM.sol` by other contracts in our implementation. The enum and the events might have ended there during development of the proxy, but are not needed in the interface anymore.

Raised PR #43 to fix this. Thanks.
